name: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
  push:
    branches:
      - "renovate/**"

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - run: corepack enable
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint (docs)
        run: pnpm lint:docs:fix

      - uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc
