name: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
    paths-ignore:
      - "docs/**"

permissions:
  contents: read

jobs:
  code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - run: corepack enable
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build (stub)
        run: pnpm build:stub

      - name: Lint (code)
        run: pnpm lint:fix

      - name: Test (unit)
        run: pnpm test:unit -u

      - name: Run build
        run: pnpm build

      - name: Assert bundle size (renovate)
        if: ${{ contains(github.head_ref, 'renovate') }}
        run: pnpm vitest run bundle

      - name: Update bundle size (renovate)
        if: failure()
        run: |
          pnpm vitest run bundle -u
          pnpm dedupe

      - name: Update bundle size
        if: ${{ !contains(github.head_ref, 'renovate') }}
        run: pnpm vitest run bundle -u

      - uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc
